services:
  - type: web
    name: image-garden
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: SECRET_KEY
        fromRender: true
      - key: DATABASE_URL
        fromRender: true
      - key: REDIS_URL
        fromRender: true
      - key: REPLICATE_API_TOKEN
        fromRender: true
      - key: RAZORPAY_KEY_ID
        fromRender: true
      - key: RAZORPAY_KEY_SECRET
        fromRender: true
      - key: SMTP_SERVER
        fromRender: true
      - key: SMTP_PORT
        fromRender: true
      - key: SMTP_USERNAME
        fromRender: true
      - key: SMTP_PASSWORD
        fromRender: true
    healthCheck:
      path: /
      timeout: 30
      interval: 60
      successThreshold: 2
      failureThreshold: 3
    autoDeploy: true

databases:
  - name: image-garden-db
    databaseName: image_garden_db
    user: image_garden_user
    region:Oregon

redis:
  - name: image-garden-redis
    region: Oregon
