services:
  - type: web
    name: image-garden
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: SECRET_KEY
        fromSecret: SECRET_KEY
      - key: DATABASE_URL
        fromSecret: DATABASE_URL
      - key: REDIS_URL
        fromSecret: REDIS_URL
      - key: REPLICATE_API_TOKEN
        fromSecret: REPLICATE_API_TOKEN
      - key: RAZORPAY_KEY_ID
        fromSecret: RAZORPAY_KEY_ID
      - key: RAZORPAY_KEY_SECRET
        fromSecret: RAZORPAY_KEY_SECRET
      - key: SMTP_SERVER
        fromSecret: SMTP_SERVER
      - key: SMTP_PORT
        fromSecret: SMTP_PORT
      - key: SMTP_USERNAME
        fromSecret: SMTP_USERNAME
      - key: SMTP_PASSWORD
        fromSecret: SMTP_PASSWORD
    autoDeploy: true

databases:
  - name: image-garden-db
    databaseName: image_garden_db
    user: image_garden_user
    region: oregon
